# Generated by Django 2.1.7 on 2019-03-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='lights',
            field=models.IntegerField(default=0),
        ),
    ]
