# Generated by Django 2.1.7 on 2019-03-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spas', '0002_auto_20190315_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='lights',
        ),
        migrations.AddField(
            model_name='person',
            name='bluetoothConnection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='hum',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='relay1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='relay2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='relay3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='relay4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='temp',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='wifiConnection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='timeIn',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='timeOut',
            field=models.TimeField(default=0),
        ),
    ]
